site_name: Polygon zkEVM Documentation
site_url: https://docs.hermez.io/
theme:
  name: material
  palette:
    primary: deep purple
  logo: logo-white.svg
  favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
repo_url: https://github.com/hermeznetwork/zkevmdoc
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/polygonhermez
    - icon: fontawesome/brands/github
      link: https://github.com/hermeznetwork/zkevmdoc
    - icon: octicons/browser-24
      link: https://hermez.io/

nav:
  - Polygon zkEVM:
    - zkEVM Overview: "zkEVM/Overview/Overview.md"
    - zkProver:
      - zkProver Overview: "zkEVM/zkProver/Overview/zkProver-Overview.md"
      - MULMOD Opcode Implementation: "zkEVM/zkProver/MulMod-Opcode/MulMod-Spec.md"
      - States Machines:
        - State Machines Overview: "zkEVM/zkProver/State-Machines/Overview/zkProver-State-Machines.md"
        # - Main State Machine:
        #   - Introduction: "zkEVM/zkProver/State-Machines/Main-State-Machine/Introduction.md"
        - Secondary State Machines:
          - Arithmetic: "zkEVM/zkProver/State-Machines/Secondary-State-Machines/Arithmetic/Arithmetic.md"
          - Storage: "zkEVM/zkProver/State-Machines/Secondary-State-Machines/Storage/Storage.md"
          - Hashing: "zkEVM/zkProver/State-Machines/Secondary-State-Machines/Hashing/Introduction.md"
          - Binary: "zkEVM/zkProver/State-Machines/Secondary-State-Machines/Binary/Binary.md"
          - Memory: "zkEVM/zkProver/State-Machines/Secondary-State-Machines/Memory/Memory.md"
          - Memory Align: "zkEVM/zkProver/State-Machines/Secondary-State-Machines/Memory-Align/Memory-Align.md"
          - Complementary: "zkEVM/zkProver/State-Machines/Secondary-State-Machines/Complementary/Complementary.md"
          - Configuration File: "zkEVM/zkProver/State-Machines/Secondary-State-Machines/Complementary/Configuration-File.md"
      # - zkASM And PIL: "zkEVM/zkProver/Architecture/zkASM-and-PIL.md"
      # - Verifiable Computations: 
        # - Introduction: "zkEVM/zkProver/Verifiable-Computations/Introduction.md"
        # - "First Example: Fibonacci": "zkEVM/zkProver/Verifiable-Computations/Fibonacci.md"
        # - Simple State Machine: "zkEVM/zkProver/Verifiable-Computations/Simple-State-Machine.md"  
        # - Modular Design: "zkEVM/zkProver/Verifiable-Computations/Modular-Design.md"  
    - zk Tooling:
      - zkASM:
        - Introduction: "zkEVM/zk-Tooling/zkASM/Introduction.md"
        - Basic Syntax: "zkEVM/zk-Tooling/zkASM/Basic-Syntax.md"
        - Some Examples: "zkEVM/zk-Tooling/zkASM/Some-Examples.md"
        - Related Repositories: "zkEVM/zk-Tooling/zkASM/Related-Repos.md"
      - PIL:
        - Introduction: "zkEVM/zk-Tooling/PIL/Introduction.md"
        - Hello Word Examples: "zkEVM/zk-Tooling/PIL/Hello-World-Examples.md"
        - Components: "zkEVM/zk-Tooling/PIL/Components.md"
        - Cyclical Nature: "zkEVM/zk-Tooling/PIL/Cyclical-Nature.md"
        - Modularity: "zkEVM/zk-Tooling/PIL/Modularity.md"
        - Advanced Features: "zkEVM/zk-Tooling/PIL/Advanced-Features.md"
        - Related Repositories: "zkEVM/zk-Tooling/PIL/Related-Repos.md"
      # - PIL-STARK:
      # - CIRCOM:
    # - Implementation (How To(s)):
    #   - How to participate in the Testnet:
    #   - How to run a zkNode:
    #   - How to be a Sequencer (for Testnet):
    #   - How to be an Aggregator (for Testnet):
    #   - How to be a Verifier (for Testnet):
    #   - How to set up L2-A to L2-B Bridge:
    # - zkNode:
    #   - Proof of Efficiency:
    #     - Introduction: "zkEVM/Proof-of-Efficiency/Introduction.md"
    #   - The Bridge:
    #     - Introduction: "zkEVM/Bridge/Introduction.md"
    - References: "zkEVM/references.md"
  - Hermez 1.0:
    - About:
      - Ethereum Scalability and zk-Rollups: "Hermez_1.0/about/scalability.md"
      - Hermez Value Proposition: "Hermez_1.0/about/value-proposition.md"
      - Hermez Network Model: "Hermez_1.0/about/model.md"
      - Security: "Hermez_1.0/about/security.md"
    - Users:
      - Hermez Wallet: "Hermez_1.0/users/hermez-wallet.md"
      - Hermez Mainnet: "Hermez_1.0/users/mainnet.md"
      - Hermez Testnet: "Hermez_1.0/users/testnet.md"
      - Exchanges: "Hermez_1.0/users/exchanges.md"
    - Developers:
      - Developer Guide: "Hermez_1.0/developers/dev-guide.md"
      - Protocol:
        - Hermez zkRollup protocol:
          - Core protocol: "Hermez_1.0/developers/protocol/hermez-protocol/protocol.md"
          - Smart contracts: "Hermez_1.0/developers/protocol/hermez-protocol/contracts/contracts.md"
          - Circuits: "Hermez_1.0/developers/protocol/hermez-protocol/circuits/circuits.md"
        - Forging consensus protocol: "Hermez_1.0/developers/protocol/consensus/consensus.md"
        - Withdrawal delayer protocol: "Hermez_1.0/developers/protocol/withdrawal-delayer/withdrawal-delayer.md"
      - Examples/SDK: "Hermez_1.0/developers/sdk.md"
      - API: "Hermez_1.0/developers/api.md"
      - Batch Explorer: "Hermez_1.0/developers/batch-explorer.md"
      - Hermez NodePrice Updater: "Hermez_1.0/developers/price-updater.md"
      - Glossary: "Hermez_1.0/developers/glossary.md"
    - FAQ:
      - End-Users: "Hermez_1.0/faq/end-users.md"
      - Integrators: "Hermez_1.0/faq/integrators.md"
      - Coordinators: "Hermez_1.0/faq/coordinators.md"
      - Proof of Donation: "Hermez_1.0/faq/pod.md"
      - Other: "Hermez_1.0/faq/other.md"
